image: jguyomard/laravel-php:7.2
services:
  - postgres:latest

variables:
  POSTGRES_DB: drypack_db
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""
  CI_DEBUG_SERVICES: trace
cache:
  paths:
  - vendor/

before_script:
- apt-get update -qq && apt-get install -y -qq git
- git --version
- chmod 777 -R storage
- chmod 777 -R bootstrap/cache
- rm .env.testing
- cp .env.ci .env.testing
- COMPOSER_PROCESS_TIMEOUT=2000 composer install

test:app:
  script:
  - ./vendor/bin/phpunit --coverage-text --colors=never



