image: php:7.2-fpm

services:
  - postgres:latest

variables:
  POSTGRES_DB: base
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""

cache:
  paths:
  - vendor/

before_script:
- apt-get update -qq && apt-get install -y -qq git
- git --version
- apt-get install -y -qq php-pgsql software-properties-common postgresql-9.5 postgresql-client-9.5
- apt-get install -y -qq postgresql-contrib-9.5 postgresql-9.5-postgis-2.2 postgresql-9.5-postgis-scripts
- php --info
- bash ci/docker_install.sh > /dev/null
- chmod 777 -R storage
- chmod 777 -R bootstrap/cache
- rm .env.testing
- cp .env.ci .env.testing
- COMPOSER_PROCESS_TIMEOUT=2000 composer install

test:app:
  script:
  - phpunit --coverage-text --colors=never
