image: jguyomard/laravel-php:7.2
services:
  - postgres:latest

variables:
  POSTGRES_DB: drypack_db
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""
  CI_DEBUG_SERVICES: trace

before_script:
- apt-get update -qq && apt-get install -y -qq git
- git --version
- chmod 777 -R storage
- chmod 777 -R bootstrap/cache
- rm .env.testing
- cp .env.ci .env.testing
- COMPOSER_PROCESS_TIMEOUT=2000 composer install

cache:
  paths:
  - vendor/

stages:
  #- build
  - test
  #- deploy

job1:
  stage: test
  script:
    - ./vendor/bin/phpunit --coverage-text --colors=never
  only:
    - develop
  artifacts:
    paths:
      - storage/logs/
      - package/app/
    expire_in: 1 day




