version: '3.1'

image: drypack-image-dev
build:
  context: docker/
volumes:
  - ./:/var/www/
cache:
  paths:
  - vendor/
before_script:
- chmod 777 -R storage
- chmod 777 -R bootstrap/cache
- COMPOSER_PROCESS_TIMEOUT=2000 composer install

test:app:
  script:
  - ./vendor/bin/phpunit --coverage-text --colors=never
