version: '3.1'

networks:
  drypack_net:
    driver: bridge
services:
  drypack_web:
    image: ttaranto/docker-nginx-php7
    networks:
      - drypack_net
    ports:
      - 80:80
    volumes:
      - ./:/var/www
    links:
      - drypack_db
  drypack_db:
    image: mdillon/postgis # can be also only 'postgres'
    networks:
      - drypack_net
    environment:
      POSTGRES_DB: drypack
      POSTGRES_USER: drypackuser
      POSTGRES_PASSWORD: drypack
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

