version: '3.1'

services:
    drypack:
        container_name: drypack-container-prod
        image: drypack-image-prod
        build:
          context: ./
          args:
            BUILD_SUPPORT: "true"
            DRYPACK_DB_USER: drypackuser
            DRYPACK_DB_PASS: drypack
            RUN_ONCE_CMD: "php artisan deploy:pack --zip=false"
            WEB_ROOT_FOLDER: "/package/app"
        ports:
          - 80:80
        environment:
          CI: "false"
        volumes:
          - ./:/var/www/

